### ISSUE TITLE
Does LC_API do anything for this mod?

### ISSUE THREAD

**Issue by YnwLNE** [Hexicube/BetterShotgun#1]
asking because I would love to use this, as this makes the shotgun actually useful, but LC_API is a nuke to a lot of other mods, hence why a lot of others have weened off of it.

**Comment by Hexicube** [comment]
Not yet, I was planning on using it for networking to sync shotgun spread.

What's the issue with it?

**Comment by YnwLNE** [comment]
> Not yet, I was planning on using it for networking to sync shotgun spread.
> 
> What's the issue with it?

generally it isn't useful for a lot of use cases and what it does it isn't the best at, hence why mods like Employee Assignments have completely removed it. Since 3.0.0 it also has a chance of breaking entire modpacks/other mods even with the recent hotfixes. I know from experience haha

**Comment by Hexicube** [comment]
May as well drop the dependency for now and see if I need to actually use it later on.
