### ISSUE TITLE
Shotgun damage bugged on the bunker spider.

### ISSUE THREAD

**Issue by SpazzMaticus107** [Hexicube/BetterShotgun#2]
No matter how accurate you shoot or how close you get the spider needs to get hit by 5 separate shotguns blasts/shells to die. Tested multiple times in LethalDevMode.

**Comment by Hexicube** [comment]
Logs for this? You can filter to lines starting with "SHOTGUN:".

**Comment by Hexicube** [comment]
Actually I removed the logging on 0.2.1, I'll need to check this myself.

**Comment by SpazzMaticus107** [comment]
Yeah just figured this out lol. If you're not going to test this in Unity then the mod I mentioned is a great help. You can toggle the test room when the ship is in the orbit. Spawned items will spawn in the ship and the enemies in the red maze under it.

**Comment by Hexicube** [comment]
Looks like this is a bug with spiders in vanilla code, all other enemies properly lose the appropriate hp but spiders don't check how much damage was dealt at once.

Vanilla shotguns go around this so I'll do the same.

**Comment by Hexicube** [comment]
Quick test shows this actually affects the vanilla shotgun too, I'm calling the same function so I've had to actually patch that function to correctly apply damage.

`
[Info   : Unity Log] Calling shoot gun....
[Info   : Unity Log] Enemies hit: 6
[Info   : Unity Log] Raycasting enemy
[Info   : Unity Log] Raycast hit wall
[Info   : Unity Log] Raycasting enemy
[Info   : Unity Log] Raycast hit wall
[Info   : Unity Log] Raycasting enemy
[Info   : Unity Log] Hit enemy, hitDamage: 3
[Info   : Unity Log] Raycasting enemy
[Info   : Unity Log] Hit enemy, hitDamage: 5
[Info   : Unity Log] Local client hit enemy SandSpider(Clone) with force of 5.
[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Info   : Unity Log] Client #0 hit enemy SandSpider(Clone) with force of 5.
[Info   : Unity Log] Raycasting enemy
[Info   : Unity Log] Hit enemy, hitDamage: 5
[Info   : Unity Log] Raycasting enemy
[Info   : Unity Log] Hit enemy, hitDamage: 3
[Info   : Unity Log] Local client hit enemy SandSpider(Clone) with force of 3.
[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Info   : Unity Log] Client #0 hit enemy SandSpider(Clone) with force of 3.
[Info   : Unity Log] Calling shoot gun and sync
[Info   : Unity Log] Shoot gun client rpc received`

Note the lack of a kill message despite sometimes doing 5 damage at once.
