### ISSUE TITLE
[0.3.1]Compatibility issues with other mods

### ISSUE THREAD

**Issue by XoF-eLtTiL** [Hexicube/BetterShotgun#4]
# Most mods are known to be affected
- More Company
- MiniMap
- SuitSaver
- etc.

Whether it's a server or client mods

**Comment by Hexicube** [comment]
That's far too vague to be useful and I've not noticed any issues with MoreCompany myself.

**Comment by XoF-eLtTiL** [comment]
Here's the main problem.
- MoreCompany will show a mods that does not display hats.
- Suit Saver Cannot be used normally
- Minimap also doesn't work properly, the GUI interface works fine, but Minimap is not displayed.

But the output console does not flag these errors

**Comment by Hexicube** [comment]
None of that is something this mod should even be capable of causing, does this happen with only this mod and those mods (plus dependencies)?

**Comment by ko0416** [comment]
Hello Hexi,

I am a friend of XoF. 

At first, we thought it would be some "big" mods or dependencies that mess up other mods. After checking our recently updated mods one by one, we can confirm that 0.3.1 does affect some mods such as MoreCompany(Host can see his own cosmetics, cannot see Client's cosmetics. Client cannot see Host's cosmetics, cannot see his own cosmetics) and SuitSaver(When clients join the lobby, they wear the orange default suits) Not sure if there are any other mods that are affected.

When we rolled back to 0.3.0(without changing any other mods or configs), everything works again. The above "bugs" are gone. I am not sure why this happens as your mod should only affect the shotguns.

Here is our Profile code - 018cb76d-b141-4316-80f0-6729039ee169

Please have a look at it.

Thank you

**Comment by Hexicube** [comment]
0.3.0 does not actually load due to mistakes, you'd have to try with 0.2.2 and 0.2.1.

I'd remove that version if I could, unfortunately thunderstore doesn't have the option.

**Comment by ko0416** [comment]
We tried 0.2.2. We did not encountered the bugs mentioned above.

**Comment by Hexicube** [comment]
Your profile code doesn't work for me.

I've tried the minimap mod solo and it appears to work fine, can't test MoreCompany cosmetics or SuitSaver right now.

My profile: 018cbae9-3722-8a20-c1bc-82b44fe82aba

**Comment by XoF-eLtTiL** [comment]
> Your profile code doesn't work for me.
> 
> I've tried the minimap mod solo and it appears to work fine, can't test MoreCompany cosmetics or SuitSaver right now.
> 
> My profile: 018cbae9-3722-8a20-c1bc-82b44fe82aba

0.2.2 doesn't have this problem, but I'm not quite sure what it is.

**Comment by Hexicube** [comment]
Was playing with friends last night, we don't have SuitSaver but we didn't have any issues with MoreCompany cosmetics.

I think you have a corrupt install. I'd suggest [going here](https://github.com/ebkr/r2modmanPlus/wiki/Why-aren%27t-my-mods-working%3F) and following the corrupt install steps.
