### ISSUE TITLE
Error when joining a lobby

### ISSUE THREAD

**Issue by Zuploader** [Hexicube/BetterShotgun#8]
Tested in LAN, create a lobby, client join, error pop everytime

Profil code: 018d4706-f995-c4ae-2c2b-43c140e73a51

[Shotgun error.log](https://github.com/Hexicube/BetterShotgun/files/14068166/Shotgun.error.log)
![Shotgun ovverride controller](https://github.com/Hexicube/BetterShotgun/assets/152256234/2f165c30-3ec8-4fcf-9694-ba99ce010ab1)

**Comment by Entity378** [comment]
@Zuploader there is an error in the code to synchronize the configs
This is because on line 109 of the config.cs file:
`FastBufferWriter blankOut = new();`
turns out to be null

I created a PR that fixes the error #9

**Comment by Zuploader** [comment]
What does this mean? Are you gonna make an update for the mod?

**Comment by Entity378** [comment]
> What does this mean? Are you gonna make an update for the mod?

It means I should have found and fixed the problem. However you have to wait for the creator of the mod to implement my fix or for him to implement his own fix.

**Comment by Hexicube** [comment]
Should be fixed with 0.3.3.
